language: ruby
rvm:
  - 2.5.1

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
#
# install: gem install jekyll html-proofer
# script: jekyll build --incremental ## && htmlproofer ./_site
#
# Or use a custom script as follows.

# set executable permission
before_script:
 - chmod +x ./script/cibuild

# run the build script
script: ./script/cibuild

branches:
  only:
    - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
